name: Cosy

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        haxe: [4.2.0]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1.1.5
        with:
          haxe-version: 4.2.0
      - name: Validate
        run: ./scripts/all_validate.sh